# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'imageviewer_gw.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(856, 557)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 473, 491))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.graphicsView = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout_2.addWidget(self.graphicsView)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 856, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget_10 = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_10.setObjectName("dockWidget_10")
        self.dockWidgetContents_10 = QtWidgets.QWidget()
        self.dockWidgetContents_10.setObjectName("dockWidgetContents_10")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.dockWidgetContents_10)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_prev = QtWidgets.QPushButton(self.dockWidgetContents_10)
        self.pushButton_prev.setObjectName("pushButton_prev")
        self.horizontalLayout_2.addWidget(self.pushButton_prev)
        self.pushButton_next = QtWidgets.QPushButton(self.dockWidgetContents_10)
        self.pushButton_next.setObjectName("pushButton_next")
        self.horizontalLayout_2.addWidget(self.pushButton_next)
        self.pushButton_zoomin = QtWidgets.QPushButton(self.dockWidgetContents_10)
        self.pushButton_zoomin.setObjectName("pushButton_zoomin")
        self.horizontalLayout_2.addWidget(self.pushButton_zoomin)
        self.pushButton_zoomout = QtWidgets.QPushButton(self.dockWidgetContents_10)
        self.pushButton_zoomout.setObjectName("pushButton_zoomout")
        self.horizontalLayout_2.addWidget(self.pushButton_zoomout)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox_text = QtWidgets.QCheckBox(self.dockWidgetContents_10)
        self.checkBox_text.setObjectName("checkBox_text")
        self.horizontalLayout.addWidget(self.checkBox_text)
        self.checkBox_bbox = QtWidgets.QCheckBox(self.dockWidgetContents_10)
        self.checkBox_bbox.setObjectName("checkBox_bbox")
        self.horizontalLayout.addWidget(self.checkBox_bbox)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.dockWidget_10.setWidget(self.dockWidgetContents_10)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_10)
        self.dockWidget_11 = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_11.setObjectName("dockWidget_11")
        self.dockWidgetContents_11 = QtWidgets.QWidget()
        self.dockWidgetContents_11.setObjectName("dockWidgetContents_11")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.dockWidgetContents_11)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.listWidget_images = QtWidgets.QListWidget(self.dockWidgetContents_11)
        self.listWidget_images.setObjectName("listWidget_images")
        self.verticalLayout_9.addWidget(self.listWidget_images)
        self.dockWidget_11.setWidget(self.dockWidgetContents_11)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_11)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Image Viewer"))
        self.dockWidget_10.setWindowTitle(_translate("MainWindow", "Controls"))
        self.pushButton_prev.setText(_translate("MainWindow", "Prev"))
        self.pushButton_next.setText(_translate("MainWindow", "Next"))
        self.pushButton_zoomin.setText(_translate("MainWindow", "Zoom In"))
        self.pushButton_zoomout.setText(_translate("MainWindow", "Zoom Out"))
        self.checkBox_text.setText(_translate("MainWindow", "Show Bbox"))
        self.checkBox_bbox.setText(_translate("MainWindow", "Show Text"))
        self.dockWidget_11.setWindowTitle(_translate("MainWindow", "Image Files"))

